spring:
  datasource:
    password: root
    url: jdbc:postgresql://172.32.0.2:5433/transportadora
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true 
  sql:
    init:
      mode=always   
